### PR TITLE
Improved Footer Design

### PR DESCRIPTION
**Pull request by Anjuli08**
I just enhanced the design of footer section.

### CODE REVIEW

**Comment by Anjuli08** [comment]
resolves issue #3

**Comment by Anjuli08** [comment]
pls review it under Hacktoberfest'22 labels

**Review by robogyan-adgitm — APPROVED** [review]

**Comment by robogyan-adgitm** [comment]
Kindly consider giving this repo a star

**Comment by robogyan-adgitm** [comment]
this does not seems to be working well :face_with_head_bandage:  @Anjuli08 

image
image

**Comment by robogyan-adgitm** [comment]
Do not forget to star the repo @Anjuli08

**Pull request merged**
