### PR TITLE
fix: third and fourth accordion faq

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
Signed-off-by: Li0 <manojrajput762000@gmail.com>

Issue #50 
Screen Recording 2022-10-07 at 9 52 40 PM

fixing functionality of third and fourth accordion 
[FAQ page link](https://robogyan-adgitm.github.io/faq.html)

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm Fixing 4th accordion

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm please review it

**Review by robogyan-adgitm — APPROVED** [review]
great

**Comment by robogyan-adgitm** [comment]
Do not forget to Star the repo

**Comment by robogyan-adgitm** [comment]
Loved the cat though :smile:

**Comment by Manoj0Marmat** [comment]
yeah desktop pet

**Comment by Manoj0Marmat** [comment]
i found lot of bug in faq page i'm raising issue kindly check

**Pull request merged**
