### PR TITLE
Background-responsiveness

### PR DESCRIPTION
**Pull request by yadavsairaj**
1. The background image has a certain correction. It shows **vectorstock footer** and their site address is shown below. [below img]
image

Corrected it and now it looks good.

2.  Website responsiveness towards the **"Apply Now" Button** was poor. Also shows a big white space below. [below img]
image

 Improved the responsiveness by adding the viewport feature and setting it to 100vh

Final website looks like this. [below img]
image

Please have a look. And after succesful merge please add the **Hacktoberfest-accepted** label. 
Thankyou :)

### CODE REVIEW

**Review by robogyan-adgitm — APPROVED** [review]

**Comment by robogyan-adgitm** [comment]
Great work @yadavsairaj

**Comment by yadavsairaj** [comment]
Thankyou glad to help.

**Comment by robogyan-adgitm** [comment]
Hope you had fun, do not forget to Star the repo

**Comment by yadavsairaj** [comment]
Sure!

**Pull request merged**
