### PR TITLE
About Section Add with theme of website 

### PR DESCRIPTION
**Pull request by iamrkaran**
About Section Add with theme of website

### CODE REVIEW

**Comment by iamrkaran** [comment]
Untitled

**Comment by robogyan-adgitm** [comment]
@iamClutchX Kindly * the repo

**Review by robogyan-adgitm — APPROVED** [review]

**Comment by iamClutchX** [comment]
please add ```hacktoberfest-accepted``` in labels

**Comment by robogyan-adgitm** [comment]
Do not forget to Star the repo, it is necessary.

**Pull request merged**
