### PR TITLE
Improve UI design of the Website

### PR DESCRIPTION
**Pull request by tahseenzahra**
This pr includes;

- hover effect on the navbar links
- update the transition as user-eye-friendly
- improved the readability style of CSS code

### CODE REVIEW

**Comment by tahseenzahra** [comment]
Hello @robogyan-adgitm can you please guide me that why the pr is spam and what test cases you have for this? so that it can be helpful for me while participating a head

**Comment by tahseenzahra** [comment]
Hello @robogyan-adgitm I have just seen the email from hacktoberfest in which I got the idea that if you just remove empty spaces or typos then it is considered spam 
*but in this pr, I haven't just done those*

As the basic purpose of the pr was to modify the UI of the webpage as listed in the title too
- the main things that were modified were to have the eye-friendly transition as to me it sounded uncomfortable to the eye because the transition of letters was too fast and was continuous
- and I learnt that to have a good user experience we should have some sort of difference while hovering on nav links so that it could be recognized easily that you are there. so I made changes to those 

whereas I considered changing the CSS file because your file had different styles throughout the code and I organized that into one style that I learned while working with microverse that our reviewers and staff there taught us.

**Comment by tahseenzahra** [comment]
I hope you will consider the PR again and if then you find anything that is stopping me from this pr to be accepted I would highly appreciate it if you can elaborate 
that will be a source of learning for me. As it is my just second time participating in an open source event

**Comment by robogyan-adgitm** [comment]
DO NOT IMPROVE THE READABILITY OF THE CODE in the future contributions.

**Comment by robogyan-adgitm** [comment]
I get it, the changes were made by a plugin. You if you can remove the conflicts I would merge the PR. Take this as an apology

**Comment by robogyan-adgitm** [comment]
I get it, the changes were made by a plugin. You if you can remove the conflicts I would merge the PR. Take this as an apology

**Comment by tahseenzahra** [comment]
> I get it, the changes were made by a plugin. You if you can remove the conflicts I would merge the PR. Take this as an apology

Thank you @robogyan-adgitm. sure I'll do that for you but I'm not getting a message here that the branch has a conflict with the main so how I could resolve the conflicts

**Comment by robogyan-adgitm** [comment]
@tahseenzahra check now

**Pull request closed without merging**
