### PR TITLE
Overlayed video on home page

### PR DESCRIPTION
**Pull request by rahulkathuriaaa**
1. Video added to home page
2. QR code added to home page
3. ADGITM located on map in contact us page

Kindy merge my repo #90

### CODE REVIEW

**Comment by robogyan-adgitm** [comment]
Can you please resolve conflicts @rahulkathuriaaa

**Comment by robogyan-adgitm** [comment]
Great work tho!!!

**Comment by rahulkathuriaaa** [comment]
Sure

**Comment by robogyan-adgitm** [comment]
I seems to have distorted the way website looks rn, maybe correct that and create another PR?

**Comment by robogyan-adgitm** [comment]
We do not have a separate mailing or have app on appstores so kindly remove that too. QR is fine but it is getting way too big.

**Pull request merged**
