### PR TITLE
Replaced the Logo's Font on Every Page

### PR DESCRIPTION
**Pull request by Aakriti-malla**
Replaced the Logo's Font to 'Russo One' from google fonts

### CODE REVIEW

**Review by robogyan-adgitm — CHANGES_REQUESTED** [review]
Can you bold the text? And remove that circle from the end too.

**Comment by robogyan-adgitm** [comment]
image
Something like this ?!

**Comment by Aakriti-malla** [comment]
Ok sure!

**Comment by robogyan-adgitm** [comment]
Changed on home page myself, just replicate that on all other pages !

**Comment by Aakriti-malla** [comment]
Removed the circle from the back and changed the font weight of the Logo for the rest of the Pages. Check it out!

**Comment by robogyan-adgitm** [comment]
Great work

**Comment by robogyan-adgitm** [comment]
You can consider staring the repo if enjoyed contributing.

**Pull request merged**
