### PR TITLE
Added hover to navbar

### PR DESCRIPTION
**Pull request by vanshgupta-2024**
Made UI improvement by adding hover effect on navbar items

### CODE REVIEW

**Comment by vanshgupta-2024** [comment]
Kindly merge the request under hacktoberfest-accepted label.
Thank you in advance!!

**Comment by robogyan-adgitm** [comment]
@vanshgupta-2024  not acceptable

**Comment by vanshgupta-2024** [comment]
@robogyan-adgitm Sorry but may i know why, so that i can improve further?

**Comment by robogyan-adgitm** [comment]
From now onwards DO NOT REMOVE SPACES AND INDENTATIONS in code, if you want to contribute such changes just create another issue. Changes like those hide legit changes you made.

**Comment by vanshgupta-2024** [comment]
Ahh alright, thank you!!

**Comment by robogyan-adgitm** [comment]
Do not forget to Star the repo

**Pull request merged**
