### PR TITLE
Added a accordion for Showing FAQs. Answers are shown in the collapsable drawer as mentioned.

### PR DESCRIPTION
**Pull request by ElectricPlant19**

### CODE REVIEW

**Review by robogyan-adgitm — APPROVED** [review]

**Comment by robogyan-adgitm** [comment]
Great work @ElectricPlant19

**Comment by ElectricPlant19** [comment]
> Great work @ElectricPlant19

aye aye

**Comment by robogyan-adgitm** [comment]
Do not forget to Star the repo

**Comment by ElectricPlant19** [comment]
> Do not forget to Star the repo

I am new  can you tell me how and what to do ?

**Pull request merged**
