### PR TITLE
To redesign Our Objective Page 

### PR DESCRIPTION
**Pull request by rahulkathuriaaa**
Designed this page with more details and eye catching UI

Kindly merge my request #124

### CODE REVIEW

**Comment by robogyan-adgitm** [comment]
remove redundancy

**Comment by rahulkathuriaaa** [comment]
done
kindly merge my request #124

**Comment by robogyan-adgitm** [comment]
I meant you have added all the contents to robogyan sub folder too, that's not necessary but for now I am adding "hacktoberfest-accepted"

**Review by robogyan-adgitm — APPROVED** [review]
Remove Robogyan sub folder as it's got redundant files

**Review by robogyan-adgitm — CHANGES_REQUESTED** [review]
Remove Robogyan sub folder as it's got redundant files

**Comment by robogyan-adgitm** [comment]
Close this one and create another PR

**Review by robogyan-adgitm — APPROVED** [review]

**Pull request merged**
